### ISSUE TITLE
Colour of Android status bar to adapt to header colours

### ISSUE THREAD

**Issue by cellyn-tan** [redbadger/pride-london-app#133]
## Description of issue

Currently, the status bar adopts a grey background colour. Ideally, we will like it to adopt the colour of the header. 

![statusbar](https://user-images.githubusercontent.com/38290023/38806385-fca9a8ec-4170-11e8-9d70-d7c70b6610c3.jpg)

**Comment by declanslevin** [comment]
This is fixed

**Comment by frigus02** [comment]
I think it is not fixed for all screen, yet. When you open the app, the status bar is still gray. Only after switching to events once, it gets blue. Then it stays blue.

**Comment by declanslevin** [comment]
Yep you're right. 

<img src="https://media.giphy.com/media/3o7abCJnPhzwYzbvDW/giphy.gif">

**Comment by JunBadger** [comment]
Chatted with @RGBboy - this is adopting the main blue for now

**Comment by RGBboy** [comment]
I'll be making a PR to sort this

**Comment by RGBboy** [comment]
Fixed in #271
